### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mohamedhamdyamer** [mohamedhamdyamer/ggt#29]
this is a serious bug!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amerfogbugz** [comment]
acknowledged!

**Comment by mohamedhamdyamer** [comment]
thanks,

**Comment by amerfogbugz** [comment]
done
