### ISSUE TITLE
a GUI bug

### ISSUE THREAD

**Issue by mohamedhamdyamer** [mohamedhamdyamer/ggt#30]
Let's resolve our simple GUI bugs :-)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amerfogbugz** [comment]
work in progress ...

**Comment by mohamedhamdyamer** [comment]
any update?

**Comment by amerfogbugz** [comment]
done
