### ISSUE TITLE
slide bar on the main page

### ISSUE THREAD

**Issue by mohamedhamdyamer** [mohamedhamdyamer/ggt#31]
we need to a slide bar on the main page to provide some flexibility to our customers!

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
slide bar on the main page.

**Describe alternatives you've considered**
Tabs at the top of the page

**Additional context**
this will provide some (actually great) flexibility to our customers!

**Comment by amerfogbugz** [comment]
good one ;-)

**Comment by mohamedhamdyamer** [comment]
done,

closing ...

**Comment by mohamedhamdyamer** [comment]
closed
